# type: ignore
"""Add chating feature

Revision ID: 68100405e15a
Revises: c048a31e131c
Create Date: 2025-05-21 17:24:27.769735

"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC
from sqlalchemy import Text  # noqa: F401

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText

# revision identifiers, used by Alembic.
revision = '68100405e15a'
down_revision = 'c048a31e131c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_1_id', sa.UUID(), nullable=False),
    sa.Column('user_2_id', sa.UUID(), nullable=False),
    sa.Column('last_message', sa.String(), nullable=True),
    sa.Column('last_message_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_1_id'], ['users.id'], name=op.f('fk_chat_sessions_user_1_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_2_id'], ['users.id'], name=op.f('fk_chat_sessions_user_2_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_sessions'))
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], name=op.f('fk_chat_messages_session_id_chat_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_address_id'), type_='unique')

    with op.batch_alter_table('user_searches', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_searches_user_id_users'), type_='foreignkey')

    with op.batch_alter_table('user_actions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_actions_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_user_actions_id'), type_='unique')

    with op.batch_alter_table('property_verifications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_property_verifications_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_property_verifications_property_id_properties'), type_='foreignkey')
        batch_op.create_foreign_key('fk_property_verifications_property_id_properties', 'properties', ['property_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_property_verifications_user_id_users', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_table('chat_messages')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
